version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/home/vscode:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
volumes:
  transferfile: